### ISSUE TITLE
TestyConfig supporting tsconfig option

### ISSUE THREAD

**Issue by ranjanified** [Testy/TestyTs#35]
Can we support "tsconfig" option via TestyConfig as well? Currently I see it being supported only as an option to CLI. Apologies if I am missing something here, as today only I came across your library, and since it looks very lightweight I am think to try it out for the good of my thin little packages that I write. Let me know your thoughts. Appreciate the idea.

**Comment by Aboisier** [comment]
Hi!

You're right, this is currently not supported.  I think it should be fairly easy and quick to implement, I should be able to do that next week!

Thanks for the suggestion 👌

**Comment by Aboisier** [comment]
Hey @ranjanified , I added support for specifying a tsconfig.json from the testy.json configuration file, as per your request (#36 ). This is now available in version 0.8.2. Please let me know if this fulfills your use case :)
