### ISSUE TITLE
Support of Comments in tsconfig.json

### ISSUE THREAD

**Issue by gbreeze** [Testy/TestyTs#41]
**Comments in i.e. tsconfig.json not supported**

`testyts
An error occured while executing the following command: C:\Program Files\nodejs\node.exe C:\Users\mail\AppData\Roaming\npm\node_modules\testyts\build\testy.js. Error: "client\tsconfig.json: Unexpected token / in JSON at position 169"`

--
Cool project, I like your approach!

lg.g.

**Comment by Aboisier** [comment]
Thanks for your feedback! This will be fixed soon. Sorry this took a while!
