### ISSUE TITLE
Enums "Undefined" unless in their own file?

### ISSUE THREAD

**Issue by ohnv** [Testy/TestyTs#56]
Is it correct that you will receive a "Cannot read property [x] of undefined" error if referencing an enum in a test file, _unless that enum is imported from a file with nothing else in it but that enum_?

**Consider the following fails:**

```
import { expect, TestSuite, Test } from 'testyts';
import { Log, LogLevel } from "../../services/logger";

@TestSuite()
export class Enum {
 
    @Test()
    CreateDB() {

        Log("This will fail with error 'Cannot read property LogLevel.Trace of undefined'", LogLevel.Trace);
    }
}
```

**However this works:**

```
import { expect, TestSuite, Test } from 'testyts';
import { Log } from "../../services/logger";
import { LogLevel } from "../../services/logger_util";

@TestSuite()
export class Enum {
 
    @Test()
    CreateDB() {

        Log("Once split into 2 files, this will run fine.", LogLevel.Trace);
    }
}
```

I had been searching for a fix for this for some time (since it appears to affect other TS test frameworks as well, including Mocha at least). After trying to copy the .tsconfig and testys.json configs with no success, I finally stumbled upon the answer by looking here. 

It seems that this is a limitation of TS itself (Please tell me if it's otherwise), so I'm not sure if this is something you can 'fix'. Perhaps a note in the documentation somewhere? Otherwise perhaps this issue itself will help others if they do a search for 'enum' like I tried.

Anyway, really like what you've done. Keep up the good work :-)

**Comment by Aboisier** [comment]
That's an interesting case! I haven't encountered it, but I'll take a look at this and try and make a repro! Thanks :)

**Comment by Aboisier** [comment]
Hi @TheTrainor , I haven't been able to reproduce your situation. Perhaps we are using different ts configurations. Do you think you could create a repl repro? Here's [my attempt](https://repl.it/@Aboisier/TestyTs-Playground-Issue-56#src/some-folder/another-one/tests.spec.ts).

**Comment by TheTrainor** [comment]
Thanks @Aboisier, it's definitely possible that something in my tsconfig was causing problems.

I will check it out as soon as I'm back from holidays and also see if using your tsconfig as shown in the repl fixes my problems. Thanks again!

**Comment by Aboisier** [comment]
Hi! Have you had the opportunity to test with my tsconfig? I'll close this for now, but feel free to reopen if this is still an issue. :)
