### ISSUE TITLE
Global timeout definition

### ISSUE THREAD

**Issue by gbreeze** [Testy/TestyTs#57]
Hey, 
would be cool if we can define a global timeout. This would be great especially testing with puppeteer or playwright.

![image](https://user-images.githubusercontent.com/1906169/100869344-3b0ab780-349d-11eb-9e7d-0e344f618883.png)

**Comment by Aboisier** [comment]
Good suggestion, I'll definitely implement that soon!

**Comment by Aboisier** [comment]
I've been working on an implementation, it is available in version 2.0.0-beta. I have to do a bit more testing because it required a a refactoring in order to bring the config info all the way to the tests. Let me know if you get the chance to test it!

**Comment by Aboisier** [comment]
Thanks for the suggestion! I've implemented it (#60) and published it. The latest version of the [vscode test explorer extension](https://marketplace.visualstudio.com/items?itemName=Testy.vscode-testyts-test-adapter) is also compatible with this new feature.

**Comment by gbreeze** [comment]
I've tested it and everything is working as expected. Thanks a lot!
