### ISSUE TITLE
Summary message - there is no "fail"

### ISSUE THREAD

**Issue by gbreeze** [Testy/TestyTs#59]
![image](https://user-images.githubusercontent.com/1906169/102597317-c41b2300-411a-11eb-911b-116f42cb1c8c.png)

Shouldn't it be `0/3 failed`?

**Comment by Aboisier** [comment]
Huh, that's weird! Did you mean `0/4 failed` though?

**Comment by Aboisier** [comment]
Thanks for reporting! The fix (#60 ) is now published.

**Comment by gbreeze** [comment]
Thanks, I tested it and the issue is corrected. 👍 

![image](https://user-images.githubusercontent.com/1906169/102768239-22493f80-4381-11eb-9772-2ffad47d8525.png)

#### Side note: 
I would not count the skipped tests to the sum count. My summary would look like:
`Summary: 3/3 passed, 0/3 failed, 1/4 skipped. (12.071s)` 

But that is as so often a matter of opinion ;-)

**Comment by Aboisier** [comment]
You're right, it would be easier to see that all the tests have passed!
