### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by A-ZC-Lau** [Testy/TestyTs#61]
I currently can't use path mapping resolution i.e `#/src/somewhere/deeper` I was wondering if this was already possible but missing in the documentation, or if there was something else I had to do.

The error is:

`error TS2307: Cannot find module`

**Comment by Aboisier** [comment]
I haven't tried it, but I'd say this isn't currently supported. It seems like this could be easily fixed using [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths). I'll try and implement this this week.

Thanks for pointing this to my attention!

**Comment by pierrelemee** [comment]
Hello @Aboisier any news on this ? I'm facing the same issue and I can't find a warkaround ...

**Comment by Aboisier** [comment]
Hi! Sorry for the delay. I've implemented this feature and released it in version [1.2.0](https://www.npmjs.com/package/testyts/v/1.2.0). Let me know if this fix works for you! I'll close this issue, but feel free to reopen it if necessary.
