### ISSUE TITLE
No "exit" on "yarn testyts" if all tasks are done.

### ISSUE THREAD

**Issue by gbreeze** [Testy/TestyTs#63]
This is related with the new global "timeout" setting in testy.json.

Problem: The yarn task "testyts" is not exiting after the test completion. The task is running at least the timeout time specified in the testy.json file. 

I.E. if there is a long timeout defined ` "timeout": 100000`, the task will only exit after this timeout.

![image](https://user-images.githubusercontent.com/1906169/104178700-13e3c600-540b-11eb-9880-4849ee5e9e24.png)

This issue brings some disadvantages:
 - VSCode Test debugger doesn't stop for a long time.
 - Long execution time for tests

Workarounds:
 - using a global install of testyts und execute the tests with `testyts` (why is it working here?) (no VSCode debugging support).
 - lower the timeout as low you can... (but a deallocated container instance can take some time to come up...)

**Comment by Aboisier** [comment]
This is fixed now, thanks for bringing this to my attention!
