### ISSUE TITLE
Readme doesn't show what to import / how to fully use this as a dependency

### ISSUE THREAD

**Issue by stealthrabbi** [Testy/TestyTs#71]
I'm having trouble figuring out what to import to use this library. The examples show impoting locally form the package. Also, where is `expect` coming from, used by the assertions.

**Comment by stealthrabbi** [comment]
A full working example showing how to use this library as a dependency imported from npm would be great.

**Comment by Aboisier** [comment]
Hi! Here's a working example. I haven't updated it to the latest version, but I think you'll get the gist. Hope this answers your question!

https://replit.com/@Aboisier/TestyTs-Playground

**Comment by stealthrabbi** [comment]
Yeah, I actually found this shortly before you posted. Very helpful. Thanks.

**Comment by Aboisier** [comment]
Glad this helped!
