### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by stealthrabbi** [Testy/TestyTs#72]
I do not see it in the comamnd line options -- is it possible to get code coverage with the `testyts` runner? I am considering migrating from Jest, where I can do `test jest --coverage` and get a coverage report.

**Comment by Aboisier** [comment]
Hi! Unfortunately, TestyTs does not have code coverage features yet. I do not think I'll be able to implement this in the short term, but PRs are welcome!

**Comment by Aboisier** [comment]
Actually, I managed to quickly whip up an example project with test coverage using [NYC](https://www.npmjs.com/package/@istanbuljs/nyc-config-typescript). 

I'll add the details in the documentation tonight. I will also probably be able to code an integration NYC packaged with TestyTs this week.

Thanks!

**Comment by stealthrabbi** [comment]
No, thank YOU!. I am fairly new to typescript and was looking for a decent unit test framework that actually let me use classes as opposed to JEST. Mainly, I wanted private helper methods and such, which I don't think JEST supports (e.g. methods to call that I don't want in actual setup/teardown. And, also wanted something that could integrate easily with vscode, and the test Coverage UI adapter for TestyTs helps with that.

Anyways, code coverage was holding me back, so this might be all I need to switch over.

**Comment by Aboisier** [comment]
Awesome, I'm glad TestyTs  answers your needs! :)
