### ISSUE TITLE
Exceptions are swallowed, and there is no way to see the line number where they are thrown.

### ISSUE THREAD

**Issue by geon** [Testy/TestyTs#79]
It would be nice to know where the errors comes from. Print at least the line number. Possibly the entire stack trace.

**Comment by Aboisier** [comment]
Thanks for filing this issue!

The logging definitely needs some improvements. I'll try and work on that this week. Any suggestions as to what the output could look like are welcome.

**Comment by geon** [comment]
Current:

```
Root
  MeshTestSuite
    √ makeEmptyMesh
    √ addEdge
    √ makeLongEdgeMesh
    x extrudeCornerOnEdge - Bad id: -1
    √ meshGraphIsValid
```

Better:
```
Root
  MeshTestSuite
    √ makeEmptyMesh
    √ addEdge
    √ makeLongEdgeMesh
    x extrudeCornerOnEdge - Bad id: -1
    √ meshGraphIsValid
```

Better:
```
Root
  MeshTestSuite
    √ makeEmptyMesh
    √ addEdge
    √ makeLongEdgeMesh
    x extrudeCornerOnEdge - Bad id: -1
    √ meshGraphIsValid
```

Better:
```
Root
  MeshTestSuite
    √ makeEmptyMesh
    √ addEdge
    √ makeLongEdgeMesh
    x extrudeCornerOnEdge - Uncaught Error: Bad id: -1
        at Object.makeTestMesh (Mesh.ts?763c:198)
        at eval (main.ts?34d3:6)
        at Object../src/main.ts (bundle.js:248)
        at __webpack_require__ (bundle.js:488)
        at bundle.js:552
        at bundle.js:555      
    √ meshGraphIsValid
```

I basically just copied how Chrome prints thrown errors.

**Comment by geon** [comment]
This also goes for `expect.not.toThrow`. If it is not expected to throw, the thrown error should probably be shown.

**Comment by Aboisier** [comment]
That's pretty clean! The stack was making the log a bit crowded, so I made the test suites bold to facilitate scanning.

![stack-demo](https://user-images.githubusercontent.com/6698529/126079836-624b9bfd-3840-4a5e-a1f5-f219b151d045.gif)

**Comment by Aboisier** [comment]
This will be deployed in version `2.0.0-beta.1` in a few minutes. Let me know if you get the change to test it!

**Comment by geon** [comment]
That looks perfect.
