### ISSUE TITLE
Upgrade TypeScript to version 4

### ISSUE THREAD

**Issue by bashlund** [Testy/TestyTs#90]
Thank you for TestyTs!

There are some nice features in TypeScript 4 (4.2.4 as I use) when declaring a name together with the return type, which I would really like TestyTs to be compatible with.

Example:
```
// Does NOT work
unpackField(image: Buffer, pointer: number): [field: Field, value: any, newPointer: number] {}
// Does work
unpackField(image: Buffer, pointer: number): [Field, any, number] {}
```

This code requires a newer version of TypeScript than TestyTs uses.

I can hack this to work with TestyTS if I manually update the version of `./node_modules/testyts/package.json` to TypeScript `4.2.4` and run `npm i` from within that directory.

Thank you!

**Comment by Aboisier** [comment]
Hi @bashlund ! Do you have a repo with a repro you could share? I tried reproducing your issue and, somehow, I am able to run the tests without having to update TestyTs's TS version. I noticed I have a recent version of typescript installed globally, perhaps this is why this works on my machine?

Thanks! :)

**Comment by Aboisier** [comment]
Huh that's odd! I'll close this for now, but let me know if this happens again!

Thanks!
