### ISSUE TITLE
Examples in readme are incomplete

### ISSUE THREAD

**Issue by thgh** [Testy/TestyTs#95]
It's missing this line:
```
import { BeforeEach, expect, Test, TestSuite } from 'testyts';
```

**Comment by Aboisier** [comment]
Hi! First of all, thanks for the suggestion! For the sake of keeping the README short, I will not add `import` statements to it. I believe most people woud find these trivial. I added a simple example project in the examples folder though, and a link to the example in the readme.

Thanks again!

**Comment by Aboisier** [comment]
Hi!

First of all, thanks for the suggestion! For the sake of keeping the README short, I will not add import statements to it. I believe most people would consider these trivial. I have added a simple example project in the examples folder though, and a link to the example in the readme. 

Your issue will also serve as documentation for anyone who runs into the following error:

> An error occured while executing the following command: C:\Program Files\nodejs\node.exe C:\some\folder\TestyTs\examples\simple\node_modules\testyts\build\testy.js. Error: "⨯ Unable to compile TypeScript:
> src/calculator.spec.ts(4,2): error TS2304: Cannot find name 'TestSuite'.
> src/calculator.spec.ts(8,4): error TS2304: Cannot find name 'BeforeEach'.
> src/calculator.spec.ts(13,4): error TS2304: Cannot find name 'Test'.
> src/calculator.spec.ts(14,4): error TS2304: Cannot find name 'TestCase'.
> src/calculator.spec.ts(15,4): error TS2304: Cannot find name 'TestCase'.
> src/calculator.spec.ts(21,5): error TS2304: Cannot find name 'expect'.


Thanks again!
